### ISSUE TITLE
bot not working

### ISSUE THREAD

**Issue by Pawansingh333** [rizmyabdulla/TapSwapBot#1]
bot not working

**Comment by rizmyabdulla** [comment]
It won't work on Termux since the `pywright` module doesn't work there. You'll need to run it on your PC. I'll try to update the bot when I have time.

**Comment by hasan1818666891** [comment]
@rizmyabdulla you can use playwright in termux-ubuntu

**Comment by rizmyabdulla** [comment]
@hasan1818666891 Yeah, I'll give it a try, or you can also contribute to the repo regarding this issue!

**Comment by Pawansingh333** [comment]
im using your bot in my PC but this is not working thanks

**Comment by rizmyabdulla** [comment]
@Pawansingh333 Can you share the problem you're facing?
